
print ("Calculadora de determinante de 3x3")
print ("Agregar numeros por fila")
numero_1 = float(input("escriba numero que se encuentra en el orden 1x1 = "))
numero_2 = float(input("escriba numero que se encuentra en el orden 1x2 = "))
numero_3 = float(input("escriba numero que se encuentra en el orden 1x3 = "))
numero_4 = float(input("escriba numero que se encuentra en el orden 2x1 = "))
numero_5 = float(input("escriba numero que se encuentra en el orden 2x2 = "))
numero_6 = float(input("escriba numero que se encuentra en el orden 2x3 = "))
numero_7 = float(input("escriba numero que se encuentra en el orden 3x1 = "))
numero_8 = float(input("escriba numero que se encuentra en el orden 3x2 = "))
numero_9 = float(input("escriba numero que se encuentra en el orden 3x3 = "))
Determinante = ((numero_1*numero_5*numero_9)+(numero_4*numero_8*numero_3)+(numero_7*numero_2*numero_6))-((numero_3*numero_5*numero_7)+(numero_6*numero_8*numero_1)+(numero_9*numero_2*numero_4))
print ("El determinante de la matriz 3x3 es {}" .format(Determinante))